# import asyncio
# from typing import Any, Dict, Literal
# from flask import Flask, json, request, jsonify
# from dotenv import load_dotenv
# import os
# import uuid
# import requests
# import json
# from pydantic import BaseModel
# from langchain_mcp_adapters.client import MultiServerMCPClient
# from langchain_ollama import ChatOllama
# from langgraph.prebuilt import create_react_agent
# from langgraph.checkpoint.memory import MemorySaver
# from langchain_core.messages import AIMessage

# load_dotenv()

# memory = MemorySaver()
# app = Flask(__name__)

# class ResourceTrackingResponse(BaseModel):
#     resource_needed_disaster_requests : list[int]
#     resources: list[Dict[str, Any]]
#     status: Literal['success', 'error'] = 'success'
#     message: str

# class ResourceTrackingAgent:
#     AGENT_CARD = {
#         "name": "RESOURCE_TRACKING_AGENT",
#         "title": "Resource Tracking Agent",
#         "description": "Track resources near disaster locations",
#         "url": "http://localhost:5012",
#         "version": "1.0",
#         "capabilities": {
#             "streaming": False,
#             "pushNotifications": False
#         }
#     }

#     SYSTEM_INSTRUCTION = (
#         "Get help_needed_requests array from previous agent response."
#         "You are a resource tracking agent. Your task is to find resource centers near verified disaster locations. "
#         "Use the track_resources tool with the disaster ID, latitude, and longitude from the verified disaster data. "
#         "Respond with a structured JSON response containing the disaster requests and resources. "
#         "The response should include:\n"
#         "- resource_needed_disaster_requests: A list of disaster request IDs that needed help.\n"
#         "- resources: Resource List with all the parameters inside, taken from tool response.\n"
#         "- status: 'success' or 'error'.\n"
#         "- message: A message describing the result.\n"
#         "If the disaster ID, latitude, or longitude is not provided, return an error message. "
#         "If parameters are missing, return an error. "
#         "Response format:\n"
#         "{\n"
#         '  "resource_needed_disaster_requests": [ ... ],\n'
#         '  "resources": [ ... ],\n'
#         '  "status": "success|error",\n'
#         '  "message": "..."\n'
#         "}"
#     )

#     def __init__(self, tools):
#         self.llm = ChatOllama(model="qwen3:4b", temperature=0.2)
#         self.tools = tools
#         self.graph = create_react_agent(
#             self.llm,
#             tools=self.tools,
#             checkpointer=memory,
#             prompt=self.SYSTEM_INSTRUCTION,
#         )

#     async def invoke(self, query, sessionId) -> str:
#         config = {'configurable': {'thread_id': sessionId}}
        
#         # Properly invoke the agent and get the final state
#         final_state = await self.graph.ainvoke(
#             {"messages": [("user", query)]},
#             config=config
#         )
#         # Process the final state
#         return self.get_agent_response(final_state, config)

#     def get_agent_response(self, state, config):
#         # Extract the structured response from the final state
#         structured_response = state.get("structured_response")
        
#         if structured_response and isinstance(structured_response, ResourceTrackingResponse):
#             return {
#                 'is_task_complete': structured_response.status == 'completed',
#                 'content': structured_response,
#             }
        
#         # Handle cases where no proper response was generated
#         return {
#             'is_task_complete': False,
#             'content': ResourceTrackingResponse(
#                 resource_needed_disaster_requests=[],
#                 resources=[{}],
#                 status='error',
#                 message="No valid response generated by the agent."
#             )
#         }


# @app.get("/.well-known/agent.json")
# def get_agent_card():
#     return jsonify(ResourceTrackingAgent.AGENT_CARD)

# async def get_agent_response(task_request,task_id):
#     try:
#         verify_data = task_request["request_verify_agent"]
#         instructions = verify_data["message"]
        
#     except (KeyError, IndexError, TypeError) as e:
#         print(f"Error extracting user text for task {task_id}: {e}")
#         return jsonify({"error": "Bad message format"}), 400
        
#     try:
#         print("Connecting to MCP servers...")
#         # Initialize the MCP client with the request count MCP server
#         client = MultiServerMCPClient(
#             {
#                 "resource_track": {
#                     "transport": "stdio",
#                     "command": "python",
#                     "args": ["disaster_agent_system/mcps/resource_track.py"]
#                 }
#             }
#         )
#         # Load tools from the MCP servers
#         print("Loading tools from MCP servers...")
#         tools = await client.get_tools()
#         print(f"Loaded {len(tools)} tools from MCP servers.")
#         # Create a ReAct agent
#         print("Creating ReAct agent...")
#         agent = ResourceTrackingAgent(tools)
#         # Run a prompt that uses the tools
#         print("Sending prompt to agent...")
#         instructions = task_request["request_verify_agent"]["message"]
#         previous_agent_response = task_request["request_verify_agent"]["request-verify-agent-response"].get("response", {})
#         full_instructions = f"{instructions}\n\n Previous agent response: {json.dumps(previous_agent_response)}"
#         print(f"Resource Tracking Agent instructions: {full_instructions}")
        
#         response = await agent.invoke(full_instructions, task_id)
#         return response
        
#     except Exception as e:
#         print(f"Error processing task {task_id}: {e}")
#         return jsonify({"error": str(e)}), 500


# # Endpoint to handle task 
# @app.post("/tasks/send")
# def handle_task():
#     RESOURCE_ALLOCATION_AGENT = "http://localhost:5013"
#     task_request = request.get_json()
    
#     if not task_request:
#         return jsonify({"error": "Invalid request"}), 400
    
#     intake_data = task_request["request_intake_agent"]
#     task_id = intake_data.get("id", str(uuid.uuid4()))
        
#     try:
#         agent_response = asyncio.run(get_agent_response(intake_data, task_id))
#         print(f"Request Verify Agent response for task {task_id}: {agent_response}")
        
#         response_content = agent_response['content']
#         response_format_dict = response_content.model_dump()
#         # Formulate A2A response Task
#         response_task = {
#             "resource-tracking-agent": {
#                 "id": task_id,
#                 "status": "success",
#                 "agent" : "resource-tracking-agent",
#                 "previous_request": task_request["request-verify-agent"]["request-verify-agent-response"].get("response", {}),
#                 "next-agent": "resource-allocation-agent",
#                 "message": "Given the available resources for each disaster request, find the suitable resources and allocate for each disaster using the tools available",
#                 "resource-tracking-agent-response": [
#                     {
#                         "role": "resource-tracking-agent",
#                         "response": response_format_dict,
#                     }
#                 ]
#             }
#         }
        
        
#         print(f"\n Forwarding task {task_id} response is \n{response_task}")
#         target_agent_url = RESOURCE_ALLOCATION_AGENT
#         target_send_url = f"{target_agent_url}/tasks/send"
#         try:
#             response = requests.post(target_send_url, json=response_task, timeout=60)
            
#         except requests.exceptions.RequestException as e:
#             print(f"Error forwarding task {task_id}: {e}")
#             response = {
#                 "resource-allocation-agent": {
#                         "id": task_id,
#                         "status": "error",
#                         "error_message": f"Error contacting target agent at {target_agent_url}: {e}",
#                         "agent": "resource-allocation-agent",
#                         "messages": [
#                         task_request.get("message", {}),
#                         {
#                             "role": "resource-allocation-agent",
#                             "error": [{"text": f"Error contacting target agent at {target_agent_url}. Details: {e}"}]
#                         }
#                 ]
#                 }
#             }
#     except Exception as e:
#         print(f"Resource Tracking Agent error: {e}")
#         response_task = {
#             "resource-tracking-agent": {
#                 "id": task_id,           
#                 "status": "error",
#                 "error_message": f"Request Verify Agent processing failed: {e}",
#                 "agent": "resource-tracking-agent",
#                 "messages": [
#                     task_request.get("message", {}),
#                     {
#                         "role": "resource-tracking-agent",
#                         "error": [{"text": f"Resource Tracking Agent failed. Details: {e}"}]
#                     }
#                 ]
#             }
#         }
#         print(f"Error response for task {task_id}: with agent verify: {response_task}")
#         response = {}
#     if not isinstance(response, dict):
#         try:
#             response = response.json()
#         except Exception:
#             response = {}
#     response_task = {
#         **response_task,**response
#     }
    
#     return jsonify(response_task)


# if __name__ == "__main__":
#     port = int(os.environ.get("PORT", 5012))
#     app.run(host="0.0.0.0", port=port)

import asyncio
import datetime
import os
from typing import Any, Dict, Literal
from flask import Flask, request, jsonify
from pydantic import BaseModel
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_ollama import ChatOllama
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver
from disaster_agent_system.models.models import DisasterRequestResponseFormat

app = Flask(__name__)
memory = MemorySaver()

class Resources(BaseModel):
    """Model for resources tracked by the agent."""
    resource_center_id: int
    location: list[float]
    name: str
    quantity: int

class ResourceTrackingResponse(BaseModel):
    disaster_data : DisasterRequestResponseFormat
    resources: list[Resources] = []
    status: Literal['success', 'error'] = 'success'
    message: str

class ResourceTrackingAgent:
    AGENT_CARD = {
        "name": "RESOURCE_TRACKING_AGENT",
        "title": "Resource Tracking Agent",
        "description": "Track resources near disaster locations",
        "url": "http://localhost:5012",
        "version": "1.0",
        "capabilities": {
            "streaming": False,
            "pushNotifications": False
        }
    }
    
    SYSTEM_INSTRUCTION = (
    "If the verification status is not 'verified', return an error with appropriate message. "
    "You are a resource tracking agent. Your task is to identify and recommend resource centers near verified disaster locations. "
    "Start by retrieving all available resources within a 10km radius using the `track_resources` tool, providing the disaster ID, latitude, and longitude from the verified disaster data. "
    "Once the nearby resources are fetched, evaluate them based on their relevance and suitability for the specific disaster request (e.g., type of disaster, needed supplies, urgency, etc.). "
    "Select the most appropriate resources from the fetched data and include them in the final response. "
    "Ensure you use the disaster data provided by the previous response (disaster ID, location, and any other context). "
    "Your structured JSON response must include:\n"
    "- disaster_data: The disaster request data in the DisasterRequestResponseFormat, which includes:\n"
    "- resources: A list of the most suitable resources selected from the (track_resources) tool response.\n"
    "- status: 'success' or 'error'.\n"
    "- message: A clear message describing what was done, including how many resources were found and how selection was made.\n"
    "If the disaster ID, latitude, or longitude is missing, return an error with an appropriate message. "
    "If tool data is missing or response is empty, return an error with explanation.\n"
    "Respond using the following format:\n"
    "{\n"
    '  "disaster_data": DisasterRequestResponseFormat,\n'
    '  "resources": list[Resources],\n'
    '  "status": "success|error",\n'
    '  "message": "..." \n'
    "}"
    )

    def __init__(self, tools):
        self.llm = ChatOllama(model="disaster_qwen_4B:latest", temperature=0.8)
        self.graph = create_react_agent(self.llm, tools=tools, checkpointer=memory,
                                        prompt=self.SYSTEM_INSTRUCTION,
                                        response_format=ResourceTrackingResponse)

    async def invoke(self, query, sessionId):
        config = {'configurable': {'thread_id': sessionId}}
        final_state = await self.graph.ainvoke({"messages": [("user", query)]}, config=config)
        return self.get_agent_response(final_state)

    def get_agent_response(self, state):
        structured_response = state.get("structured_response")
        if structured_response and isinstance(structured_response, ResourceTrackingResponse):
            return {
                'is_task_complete': True,
                'content': structured_response.model_dump(),
            }
        # Return error format if structured response is missing or wrong
        return {
            'is_task_complete': False,
            'content': {
                "disaster_data": DisasterRequestResponseFormat(
                    status = 'error',
                    request_id = 0,
                    disaster = 'unknown',
                    disasterId=0,
                    disaster_status = 'medium',
                    location = [0.0, 0.0],
                    time = '2023-11-15T10:00:00Z',
                    affected_count = 0,
                    contact_info = 'Not applicable',
                    image_description = 'Not applicable',
                    voice_description = 'Not applicable',
                    text_description = 'Not applicable'),
                "resources": [],
                "status": "error",
                "message": "No valid response generated by the agent."
            }
        }

@app.get("/.well-known/agent.json")
def get_tracking_agent_card():
    return jsonify(ResourceTrackingAgent.AGENT_CARD)

async def get_tracking_agent_response(task_request, task_id):
    try:
        # Initialize tools and agent
        client = MultiServerMCPClient(
        {
            # "resource-track": {
            #     "transport": "stdio", 
            #     "command": "python",
            #     "args": ["disaster_agent_system/mcps/resource_track.py"]
            # }
            "mcp-server": 
            {
            "transport": "stdio", 
            "command": "python",
            "args": ["disaster_agent_system/mcps/mcp_server.py"]}
        })
        tools = await client.get_tools()
        print(f"Loaded {len(tools)} tools from MCP servers.")
        print("Creating Resource Tracking Agent...")
        agent = ResourceTrackingAgent(tools)
        # Pass the intake response as instruction text
        return await agent.invoke(str(task_request), task_id)
    except Exception as e:
        # Return error content on exception
        return {
            "error": str(e), 
            "content": {
                "disaster_data": DisasterRequestResponseFormat(
                    status='error',
                    request_id=0,
                    disaster_status='medium',
                    disaster='unknown',
                    disasterId=0,
                    location=[0.0, 0.0],
                    time=datetime.datetime.now().isoformat(),
                    affected_count=0,
                    contact_info='Not applicable',
                    image_description='Not applicable',
                    voice_description='Not applicable',
                    text_description='Not applicable'),
                "resources": [],
                "status": "error",
                "message": f"Error: {str(e)}"}
            }

@app.post("/tasks/send")
def handle_tracking_task():
    task_request = request.get_json()
    # print(f"Received task request for Resource Tracking Agent: {task_request}")
    if not task_request:
        return jsonify({"error": "Invalid request"}), 400
    agent_responses = task_request.get("agent_responses", [])
    # Extract the response dict for "request-intake-agent" to another variable
    request_verify_agent = next((agent_resp.get("response") for agent_resp in agent_responses if agent_resp.get("agent") == "request-verify-agent"),None)
    task_id = request_verify_agent.get("id", "") if request_verify_agent is not None else ""
    print(f"Processing task {task_id} with agent responses: {agent_responses}")
    try:
        agent_response = asyncio.run(get_tracking_agent_response(request_verify_agent, task_id))
        print(f"Resource Tracking Agent response for task {task_id}: {agent_response}")
    except Exception as e:
        agent_response = {
            "error": str(e), 
            "content": {
                "resource_needed_disaster_requests": [],
                "resources": [],
                "status": "error",
                "message": f"Error processing task {task_id}: {str(e)}"
        }}

    # If the agent did not complete successfully, return HTTP 500 with status="error"
    if not agent_response.get("is_task_complete", False):
        response = jsonify({
            "resource-tracking-agent": {
                "id": task_id,
                "status": "error",
                "response": agent_response.get("content", {})
            },
            "agent_responses": task_request.get("agent_responses", [])
        })
        response.status_code = 500
        return response

    # Success: return status="success"
    return jsonify({
        "resource-tracking-agent": {
            "id": task_id,
            "status": "success",
            "response": agent_response.get("content", {})
        },
        "agent_responses": task_request.get("agent_responses", [])
    })

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5012))
    print(f"Resource Tracking Agent server starting on port {port}")
    app.run(host="0.0.0.0", port=port) 
