import asyncio
from typing import Any, Dict, Literal
from flask import Flask, json, request, jsonify
from dotenv import load_dotenv
import os
import uuid
import requests
import json
from pydantic import BaseModel
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_ollama import ChatOllama
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.messages import AIMessage

load_dotenv()

memory = MemorySaver()
app = Flask(__name__)

class ResourceTrackingResponse(BaseModel):
    resource_needed_disaster_requests : list[int]
    resources: list[Dict[str, Any]]
    status: Literal['success', 'error'] = 'success'
    message: str

class ResourceTrackingAgent:
    AGENT_CARD = {
        "name": "RESOURCE_TRACKING_AGENT",
        "title": "Resource Tracking Agent",
        "description": "Track resources near disaster locations",
        "url": "http://localhost:5012",
        "version": "1.0",
        "capabilities": {
            "streaming": False,
            "pushNotifications": False
        }
    }

    SYSTEM_INSTRUCTION = (
        "Get help_needed_requests array from previous agent response."
        "You are a resource tracking agent. Your task is to find resource centers near verified disaster locations. "
        "Use the track_resources tool with the disaster ID, latitude, and longitude from the verified disaster data. "
        "Respond with a structured JSON response containing the disaster requests and resources. "
        "The response should include:\n"
        "- resource_needed_disaster_requests: A list of disaster request IDs that needed help.\n"
        "- resources: Resource List with all the parameters inside, taken from tool response.\n"
        "- status: 'success' or 'error'.\n"
        "- message: A message describing the result.\n"
        "If the disaster ID, latitude, or longitude is not provided, return an error message. "
        "If parameters are missing, return an error. "
        "Response format:\n"
        "{\n"
        '  "resource_needed_disaster_requests": [ ... ],\n'
        '  "resources": [ ... ],\n'
        '  "status": "success|error",\n'
        '  "message": "..."\n'
        "}"
    )

    def __init__(self, tools):
        self.llm = ChatOllama(model="qwen3:4b", temperature=0.2)
        self.tools = tools
        self.graph = create_react_agent(
            self.llm,
            tools=self.tools,
            checkpointer=memory,
            prompt=self.SYSTEM_INSTRUCTION,
        )

    async def invoke(self, query, sessionId) -> str:
        config = {'configurable': {'thread_id': sessionId}}
        
        # Properly invoke the agent and get the final state
        final_state = await self.graph.ainvoke(
            {"messages": [("user", query)]},
            config=config
        )
        # Process the final state
        return self.get_agent_response(final_state, config)

    def get_agent_response(self, state, config):
        # Extract the structured response from the final state
        structured_response = state.get("structured_response")
        
        if structured_response and isinstance(structured_response, ResourceTrackingResponse):
            return {
                'is_task_complete': structured_response.status == 'completed',
                'content': structured_response,
            }
        
        # Handle cases where no proper response was generated
        return {
            'is_task_complete': False,
            'content': ResourceTrackingResponse(
                resource_needed_disaster_requests=[],
                resources=[{}],
                status='error',
                message="No valid response generated by the agent."
            )
        }


@app.get("/.well-known/agent.json")
def get_agent_card():
    return jsonify(ResourceTrackingAgent.AGENT_CARD)

async def get_agent_response(task_request,task_id):
    try:
        verify_data = task_request["request_verify_agent"]
        instructions = verify_data["message"]
        
    except (KeyError, IndexError, TypeError) as e:
        print(f"Error extracting user text for task {task_id}: {e}")
        return jsonify({"error": "Bad message format"}), 400
        
    try:
        print("Connecting to MCP servers...")
        # Initialize the MCP client with the request count MCP server
        client = MultiServerMCPClient(
            {
                "resource_track": {
                    "transport": "stdio",
                    "command": "python",
                    "args": ["disaster_agent_system/mcps/resource_track.py"]
                }
            }
        )
        # Load tools from the MCP servers
        print("Loading tools from MCP servers...")
        tools = await client.get_tools()
        print(f"Loaded {len(tools)} tools from MCP servers.")
        # Create a ReAct agent
        print("Creating ReAct agent...")
        agent = ResourceTrackingAgent(tools)
        # Run a prompt that uses the tools
        print("Sending prompt to agent...")
        instructions = task_request["request_verify_agent"]["message"]
        previous_agent_response = task_request["request_verify_agent"]["request-verify-agent-response"].get("response", {})
        full_instructions = f"{instructions}\n\n Previous agent response: {json.dumps(previous_agent_response)}"
        print(f"Resource Tracking Agent instructions: {full_instructions}")
        
        response = await agent.invoke(full_instructions, task_id)
        return response
        
    except Exception as e:
        print(f"Error processing task {task_id}: {e}")
        return jsonify({"error": str(e)}), 500


# Endpoint to handle task 
@app.post("/tasks/send")
def handle_task():
    RESOURCE_ALLOCATION_AGENT = "http://localhost:5013"
    task_request = request.get_json()
    
    if not task_request:
        return jsonify({"error": "Invalid request"}), 400
    
    intake_data = task_request["request_intake_agent"]
    task_id = intake_data.get("id", str(uuid.uuid4()))
        
    try:
        agent_response = asyncio.run(get_agent_response(intake_data, task_id))
        print(f"Request Verify Agent response for task {task_id}: {agent_response}")
        
        response_content = agent_response['content']
        response_format_dict = response_content.model_dump()
        # Formulate A2A response Task
        response_task = {
            "resource-tracking-agent": {
                "id": task_id,
                "status": "success",
                "agent" : "resource-tracking-agent",
                "previous_request": task_request["request-verify-agent"]["request-verify-agent-response"].get("response", {}),
                "next-agent": "resource-allocation-agent",
                "message": "Given the available resources for each disaster request, find the suitable resources and allocate for each disaster using the tools available",
                "resource-tracking-agent-response": [
                    {
                        "role": "resource-tracking-agent",
                        "response": response_format_dict,
                    }
                ]
            }
        }
        
        
        print(f"\n Forwarding task {task_id} response is \n{response_task}")
        target_agent_url = RESOURCE_ALLOCATION_AGENT
        target_send_url = f"{target_agent_url}/tasks/send"
        try:
            response = requests.post(target_send_url, json=response_task, timeout=60)
            
        except requests.exceptions.RequestException as e:
            print(f"Error forwarding task {task_id}: {e}")
            response = {
                "resource-allocation-agent": {
                        "id": task_id,
                        "status": "error",
                        "error_message": f"Error contacting target agent at {target_agent_url}: {e}",
                        "agent": "resource-allocation-agent",
                        "messages": [
                        task_request.get("message", {}),
                        {
                            "role": "resource-allocation-agent",
                            "error": [{"text": f"Error contacting target agent at {target_agent_url}. Details: {e}"}]
                        }
                ]
                }
            }
    except Exception as e:
        print(f"Resource Tracking Agent error: {e}")
        response_task = {
            "resource-tracking-agent": {
                "id": task_id,           
                "status": "error",
                "error_message": f"Request Verify Agent processing failed: {e}",
                "agent": "resource-tracking-agent",
                "messages": [
                    task_request.get("message", {}),
                    {
                        "role": "resource-tracking-agent",
                        "error": [{"text": f"Resource Tracking Agent failed. Details: {e}"}]
                    }
                ]
            }
        }
        print(f"Error response for task {task_id}: with agent verify: {response_task}")
        response = {}
    if not isinstance(response, dict):
        try:
            response = response.json()
        except Exception:
            response = {}
    response_task = {
        **response_task,**response
    }
    
    return jsonify(response_task)


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5012))
    app.run(host="0.0.0.0", port=port)