import asyncio
from typing import Any, Dict, Literal
from flask import Flask, request, jsonify
from dotenv import load_dotenv
import os
import uuid
import requests
import json
from pydantic import BaseModel
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_ollama import ChatOllama
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver

load_dotenv()

memory = MemorySaver()
app = Flask(__name__)

class AssignedResource(BaseModel):
    disaster_id: int
    resource_id: int
    amount: int

class ResourceAssignResponse(BaseModel):
    assigned_resources: list[AssignedResource]
    status: Literal['success', 'error'] = 'success'
    message: str

class ResourceAssignAgent:
    AGENT_CARD = {
        "name": "RESOURCE_ASSIGN_AGENT",
        "title": "Resource Assign Agent",
        "description": "Assign resources to disaster requests based on tracking agent response",
        "url": "http://localhost:5014",
        "version": "1.0",
        "capabilities": {
            "streaming": False,
            "pushNotifications": False
        }
    }

    SYSTEM_INSTRUCTION = (
        '''
        "You are a resource assignment agent. Your task is to assign available resources to disaster requests "
        "based on the response from the resource tracking agent. Use the assign_resources tool with the disaster "
        "you should select a suitable amount from the count and used values in the resources available"
        "There can be multiple resources for a single disaster request. "
        "Respond with a structured JSON response containing the assigned resources. "
        "If parameters are missing, return an error. "
        "Response format:\n"
        "{\n"
        '  "assigned_resources": { "disaster_id": int, "resource_id": int, "amount": int } ,\n'
        '  "status": "success|error",\n'
        '  "message": "..."\n'
        "}"
        '''
    )

    def __init__(self, tools):
        self.llm = ChatOllama(model="qwen3:4b", temperature=0.2)
        self.tools = tools
        self.graph = create_react_agent(
            self.llm,
            tools=self.tools,
            checkpointer=memory,
            prompt=self.SYSTEM_INSTRUCTION,
        )

    async def invoke(self, query, sessionId) -> dict:
        config = {'configurable': {'thread_id': sessionId}}
        final_state = await self.graph.ainvoke(
            {"messages": [("user", query)]},
            config=config
        )
        return self.get_agent_response(final_state, config)

    def get_agent_response(self, state, config):
        structured_response = state.get("structured_response")
        if structured_response and isinstance(structured_response, ResourceAssignResponse):
            return {
                'is_task_complete': structured_response.status == 'success',
                'content': structured_response,
            }
        return {
            'is_task_complete': False,
            'content': ResourceAssignResponse(
                assigned_resources=[],
                status='error',
                message="No valid response generated by the agent."
            )
        }

@app.get("/.well-known/agent.json")
def get_agent_card():
    return jsonify(ResourceAssignAgent.AGENT_CARD)

async def get_agent_response(task_request, task_id):
    try:
        tracking_data = task_request["resource-tracking-agent"]
        tracking_response = tracking_data.get("resource-tracking-agent-response", [{}])[0].get("response", {})
        instructions = (
            "Assign resources to the following disaster request using the available resources.\n"
            f"Disaster Request: {json.dumps(tracking_response.get('help_needed_requests', {}))}\n"
        )
    except (KeyError, IndexError, TypeError) as e:
        print(f"Error extracting tracking agent response for task {task_id}: {e}")
        return {
            "resource-assign-agent": {
                "id": task_id,
                "status": "error",
                "agent": "resource-assign-agent",
                "error_message": "Bad message format",
                "messages": [
                    task_request.get("message", {}),
                    {
                        "role": "resource-assign-agent",
                        "error": [{"text": f"Error extracting tracking agent response for task {task_id}: {e}"}]
                    }
                ]
            }
        }
    try:
        print("Connecting to MCP servers for assignment tools...")
        client = MultiServerMCPClient(
            {
                "assign-resources": {
                    "transport": "stdio",
                    "command": "python",
                    "args": ["disaster_agent_system/mcps/assign_resources.py"]
                }
            }
        )
        print("Loading tools from MCP servers...")
        tools = await client.get_tools()
        print(f"Loaded {len(tools)} tools from MCP servers.")
        print("Creating ResourceAssignAgent...")
        agent = ResourceAssignAgent(tools)
        print("Sending prompt to agent...")
        print(f"Agent instructions: {instructions}")
        response = await agent.invoke(instructions, task_id)
        return response
    except Exception as e:
        print(f"Error processing task {task_id}: {e}")
        return jsonify({"error": str(e)}), 500

@app.post("/tasks/send")
def handle_task():
    TASK_PRIORITIZE_AGENT = "http://localhost:5015"
    task_request = request.get_json()
    if not task_request:
        return jsonify({"error": "Invalid request"}), 400
    intake_data = task_request
    task_id = intake_data.get("id", str(uuid.uuid4()))
    try:
        agent_response = asyncio.run(get_agent_response(intake_data, task_id))
        print(f"Resource Assign Agent response for task {task_id}: {agent_response}")
        response_content = agent_response['content']
        response_format_dict = response_content.model_dump()
        response_task = {
            "resource-assign-agent": {
                "id": task_id,
                "status": "success",
                "agent": "resource-assign-agent",
                "previous_request": intake_data.get("resource-tracking-agent", {}),
                "next-agent": "task-prioritize-agent",
                "message": "Resources have been assigned to the disaster request.",
                "resource-assign-agent-response": [
                    {
                        "role": "resource-assign-agent",
                        "response": response_format_dict,
                    }
                ]
            }
        }
        print(f"\n Forwarding task {task_id} response is \n{response_task}")
        target_agent_url = TASK_PRIORITIZE_AGENT
        target_send_url = f"{target_agent_url}/tasks/send"
        try:
            response = requests.post(target_send_url, json=response_task, timeout=60)
        except requests.exceptions.RequestException as e:
            print(f"Error forwarding task {task_id}: {e}")
            response = {
                "resource-assign-agent": {
                    "id": task_id,
                    "status": "error",
                    "error_message": f"Error contacting target agent at {target_agent_url}: {e}",
                    "agent": "resource-assign-agent",
                    "messages": [
                        intake_data.get("message", {}),
                        {
                            "role": "resource-assign-agent",
                            "error": [{"text": f"Error contacting target agent at {target_agent_url}. Details: {e}"}]
                        }
                    ]
                }
            }
    except Exception as e:
        print(f"Resource Assign Agent error: {e}")
        response_task = {
            "resource-assign-agent": {
                "id": task_id,
                "status": "error",
                "error_message": f"Resource Assign Agent processing failed: {e}",
                "agent": "resource-assign-agent",
                "messages": [
                    intake_data.get("message", {}),
                    {
                        "role": "resource-assign-agent",
                        "error": [{"text": f"Assignment agent failed. Details: {e}"}]
                    }
                ]
            }
        }
        print(f"Error response for task {task_id}: {response_task}")
        response = {}
    if not isinstance(response, dict):
        try:
            response = response.json()
        except Exception:
            response = {}
    response_task = {
        **response_task, **response
    }
    return jsonify(response_task)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5013))
    app.run(host="0.0.0.0", port=port)