# import asyncio
# from typing import Any, Dict, Literal
# from flask import Flask, request, jsonify
# from dotenv import load_dotenv
# import os
# import uuid
# import requests
# import json
# from pydantic import BaseModel
# from langchain_mcp_adapters.client import MultiServerMCPClient
# from langchain_ollama import ChatOllama
# from langgraph.prebuilt import create_react_agent
# from langgraph.checkpoint.memory import MemorySaver

# load_dotenv()

# memory = MemorySaver()
# app = Flask(__name__)

# class AssignedResource(BaseModel):
#     disaster_id: int
#     resource_id: int
#     amount: int

# class ResourceAssignResponse(BaseModel):
#     assigned_resources: list[AssignedResource]
#     status: Literal['success', 'error'] = 'success'
#     message: str

# class ResourceAssignAgent:
#     AGENT_CARD = {
#         "name": "RESOURCE_ASSIGN_AGENT",
#         "title": "Resource Assign Agent",
#         "description": "Assign resources to disaster requests based on tracking agent response",
#         "url": "http://localhost:5014",
#         "version": "1.0",
#         "capabilities": {
#             "streaming": False,
#             "pushNotifications": False
#         }
#     }

#     SYSTEM_INSTRUCTION = (
#         '''
#         "You are a resource assignment agent. Your task is to assign available resources to disaster requests "
#         "based on the response from the resource tracking agent. Use the assign_resources tool with the disaster "
#         "you should select a suitable amount from the count and used values in the resources available"
#         "There can be multiple resources for a single disaster request. "
#         "Respond with a structured JSON response containing the assigned resources. "
#         "If parameters are missing, return an error. "
#         "Response format:\n"
#         "{\n"
#         '  "assigned_resources": { "disaster_id": int, "resource_id": int, "amount": int } ,\n'
#         '  "status": "success|error",\n'
#         '  "message": "..."\n'
#         "}"
#         '''
#     )

#     def __init__(self, tools):
#         self.llm = ChatOllama(model="qwen3:4b", temperature=0.2)
#         self.tools = tools
#         self.graph = create_react_agent(
#             self.llm,
#             tools=self.tools,
#             checkpointer=memory,
#             prompt=self.SYSTEM_INSTRUCTION,
#         )

#     async def invoke(self, query, sessionId) -> dict:
#         config = {'configurable': {'thread_id': sessionId}}
#         final_state = await self.graph.ainvoke(
#             {"messages": [("user", query)]},
#             config=config
#         )
#         return self.get_agent_response(final_state, config)

#     def get_agent_response(self, state, config):
#         structured_response = state.get("structured_response")
#         if structured_response and isinstance(structured_response, ResourceAssignResponse):
#             return {
#                 'is_task_complete': structured_response.status == 'success',
#                 'content': structured_response,
#             }
#         return {
#             'is_task_complete': False,
#             'content': ResourceAssignResponse(
#                 assigned_resources=[],
#                 status='error',
#                 message="No valid response generated by the agent."
#             )
#         }

# @app.get("/.well-known/agent.json")
# def get_agent_card():
#     return jsonify(ResourceAssignAgent.AGENT_CARD)

# async def get_agent_response(task_request, task_id):
#     try:
#         tracking_data = task_request["resource-tracking-agent"]
#         tracking_response = tracking_data.get("resource-tracking-agent-response", [{}])[0].get("response", {})
#         instructions = (
#             "Assign resources to the following disaster request using the available resources.\n"
#             f"Disaster Request: {json.dumps(tracking_response.get('help_needed_requests', {}))}\n"
#         )
#     except (KeyError, IndexError, TypeError) as e:
#         print(f"Error extracting tracking agent response for task {task_id}: {e}")
#         return {
#             "resource-assign-agent": {
#                 "id": task_id,
#                 "status": "error",
#                 "agent": "resource-assign-agent",
#                 "error_message": "Bad message format",
#                 "messages": [
#                     task_request.get("message", {}),
#                     {
#                         "role": "resource-assign-agent",
#                         "error": [{"text": f"Error extracting tracking agent response for task {task_id}: {e}"}]
#                     }
#                 ]
#             }
#         }
#     try:
#         print("Connecting to MCP servers for assignment tools...")
#         client = MultiServerMCPClient(
#             {
#                 "assign-resources": {
#                     "transport": "stdio",
#                     "command": "python",
#                     "args": ["disaster_agent_system/mcps/assign_resources.py"]
#                 }
#             }
#         )
#         print("Loading tools from MCP servers...")
#         tools = await client.get_tools()
#         print(f"Loaded {len(tools)} tools from MCP servers.")
#         print("Creating ResourceAssignAgent...")
#         agent = ResourceAssignAgent(tools)
#         print("Sending prompt to agent...")
#         print(f"Agent instructions: {instructions}")
#         response = await agent.invoke(instructions, task_id)
#         return response
#     except Exception as e:
#         print(f"Error processing task {task_id}: {e}")
#         return jsonify({"error": str(e)}), 500

# @app.post("/tasks/send")
# def handle_task():
#     TASK_PRIORITIZE_AGENT = "http://localhost:5015"
#     task_request = request.get_json()
#     if not task_request:
#         return jsonify({"error": "Invalid request"}), 400
#     intake_data = task_request
#     task_id = intake_data.get("id", str(uuid.uuid4()))
#     try:
#         agent_response = asyncio.run(get_agent_response(intake_data, task_id))
#         print(f"Resource Assign Agent response for task {task_id}: {agent_response}")
#         response_content = agent_response['content']
#         response_format_dict = response_content.model_dump()
#         response_task = {
#             "resource-assign-agent": {
#                 "id": task_id,
#                 "status": "success",
#                 "agent": "resource-assign-agent",
#                 "previous_request": intake_data.get("resource-tracking-agent", {}),
#                 "next-agent": "task-prioritize-agent",
#                 "message": "Resources have been assigned to the disaster request.",
#                 "resource-assign-agent-response": [
#                     {
#                         "role": "resource-assign-agent",
#                         "response": response_format_dict,
#                     }
#                 ]
#             }
#         }
#         print(f"\n Forwarding task {task_id} response is \n{response_task}")
#         target_agent_url = TASK_PRIORITIZE_AGENT
#         target_send_url = f"{target_agent_url}/tasks/send"
#         try:
#             response = requests.post(target_send_url, json=response_task, timeout=60)
#         except requests.exceptions.RequestException as e:
#             print(f"Error forwarding task {task_id}: {e}")
#             response = {
#                 "resource-assign-agent": {
#                     "id": task_id,
#                     "status": "error",
#                     "error_message": f"Error contacting target agent at {target_agent_url}: {e}",
#                     "agent": "resource-assign-agent",
#                     "messages": [
#                         intake_data.get("message", {}),
#                         {
#                             "role": "resource-assign-agent",
#                             "error": [{"text": f"Error contacting target agent at {target_agent_url}. Details: {e}"}]
#                         }
#                     ]
#                 }
#             }
#     except Exception as e:
#         print(f"Resource Assign Agent error: {e}")
#         response_task = {
#             "resource-assign-agent": {
#                 "id": task_id,
#                 "status": "error",
#                 "error_message": f"Resource Assign Agent processing failed: {e}",
#                 "agent": "resource-assign-agent",
#                 "messages": [
#                     intake_data.get("message", {}),
#                     {
#                         "role": "resource-assign-agent",
#                         "error": [{"text": f"Assignment agent failed. Details: {e}"}]
#                     }
#                 ]
#             }
#         }
#         print(f"Error response for task {task_id}: {response_task}")
#         response = {}
#     if not isinstance(response, dict):
#         try:
#             response = response.json()
#         except Exception:
#             response = {}
#     response_task = {
#         **response_task, **response
#     }
#     return jsonify(response_task)

# if __name__ == "__main__":
#     port = int(os.environ.get("PORT", 5013))
#     app.run(host="0.0.0.0", port=port)


import asyncio
import datetime
import os
from typing import Any, Dict
from flask import Flask, request, jsonify
from pydantic import BaseModel
from disaster_agent_system.models.models import DisasterRequestResponseFormat
from langchain_mcp_adapters.client import MultiServerMCPClient
from langchain_ollama import ChatOllama
from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver

app = Flask(__name__)
memory = MemorySaver()

class ResourceAllocations(BaseModel):
    resource_allocations : list[Dict[str,Any]] = []  # List of resource allocations for each disaster request
    status: str
    message: str

class ResourceAllocationAgent:
    AGENT_CARD = {
        "name": "RESOURCE_ASSIGN_AGENT",
        "title": "Resource Assign Agent",
        "description": "Assigns available resources from nearby resource centers to verified disaster requests.",
        "url": "http://localhost:5013",
        "version": "1.0",
        "capabilities": {
            "streaming": False,
            "pushNotifications": False
        }
    }

    SYSTEM_INSTRUCTION = (
        "You are a resource assignment agent. Your task is to assign available resources to disaster requests "
        "based on the output from the resource tracking agent. You must use the available information including disaster ID, "
        "resource ID, available quantity, and disaster needs to determine suitable allocations.\n\n"

        "Use the `assign_resources` and pass parameters as (request_id: int, resource_center_ids: list[int], amounts: list[int]) to the tool to perform the assignment. Make sure that:\n"
        "Then call change_status_after_assign_resources with parameters as (request_id: int, status: str)"
        "- You only assign resources that are available (i.e., not already fully allocated).\n"
        "- For each disaster request, select the most suitable resource centers based on proximity and availability.\n"
        "- Use fields: `disasterRequestId`, `resourceCenterId`, `amount`, and set `isAllocated` to `true`.\n"
        "- If no resources can be assigned, return an error status and a message explaining why.\n\n"

        "Respond in the following JSON format:\n"
        "{\n"
        '  "assigned_resources": [\n'
        "     { \"disaster_id\": int, \"resource_id\": int, \"amount\": int, \"is_allocated\": true }\n"
        "  ],\n"
        '  "status": "success" | "error",\n'
        '  "message": "Describe what was done or why an error occurred."\n'
        "}\n\n"

        "If any required fields (like disaster ID or resource availability) are missing from the input, "
        "return status='error' and include an appropriate message.\n"

        "Always aim to optimize resource use and minimize unmet needs."
    )

    def __init__(self, tools):
        self.llm = ChatOllama(model="qwen3:4b", temperature=0.8)
        self.graph = create_react_agent(self.llm, tools=tools, checkpointer=memory,
                                        prompt=self.SYSTEM_INSTRUCTION,
                                        response_format=ResourceAllocations)

    async def invoke(self, query, sessionId):
        config = {'configurable': {'thread_id': sessionId}}
        final_state = await self.graph.ainvoke({"messages": [("user", query)]}, config=config)
        return self.get_agent_response(final_state)

    def get_agent_response(self, state):
        structured_response = state.get("structured_response")
        if structured_response and isinstance(structured_response, ResourceAllocations):
            return {
                'is_task_complete': True,
                'content': structured_response.model_dump(),
            }
        # Return error format if structured response is missing or wrong
        return {
            'is_task_complete': False,
            'content': {
                "help_needed_requests": [],
                "status": "error",
                "verification_status": "not_verified",
                "verification_message": "Failed to generate proper response"
            }
        }

@app.get("/.well-known/agent.json")
def get_verify_agent_card():
    return jsonify(ResourceAllocationAgent.AGENT_CARD)

async def get_verify_agent_response(task_request, task_id):
    try:
        # Initialize tools and agent
        client = MultiServerMCPClient(
        {
            # "resource-assign": {
            #     "transport": "stdio", 
            #     "command": "python",
            #     "args": ["disaster_agent_system/mcps/resource_assign.py"]
            # }
            "mcp-server": 
            {
            "transport": "stdio", 
            "command": "python",
            "args": ["disaster_agent_system/mcps/mcp_server.py"]}
        })
        tools = await client.get_tools()
        print(f"Loaded {len(tools)} tools from MCP servers.")
        print("Creating Request Verify Agent...")
        agent = ResourceAllocationAgent(tools)
        # Pass the intake response as instruction text
        return await agent.invoke(str(task_request), task_id)
    except Exception as e:
        # Return error content on exception
        return {
            "error": str(e), 
            "content": {
                "resource_allocations": [],
                "status": "error",
                "message": f"Error processing task {task_id}: {str(e)}"
        }}

@app.post("/tasks/send")
def handle_verify_task():
    task_request = request.get_json()
    # print(f"Received task request for Resource Allocation Agent: {task_request}")
    if not task_request:
        return jsonify({"error": "Invalid request"}), 400
    agent_responses = task_request.get("agent_responses", [])
    # Extract the response dict for "request-intake-agent" to another variable
    resource_tracking_agent = next(
        (agent_resp.get("response") for agent_resp in agent_responses if agent_resp.get("agent") == "resource-tracking-agent"),
        None
    )
    task_id = resource_tracking_agent.get("id", "") if resource_tracking_agent is not None else ""
    try:
        agent_response = asyncio.run(get_verify_agent_response(resource_tracking_agent, task_id))
        print(f"Resource Allocation Agent response for task {task_id}: {agent_response}")
    except Exception as e:
        agent_response = {
            "error": str(e), 
            "content": {
            "resource_allocations": [],
            "status": "error",
            "message": f"Error processing task {task_id}: {str(e)}"
        }}

    # If the agent did not complete successfully, return HTTP 500 with status="error"
    if not agent_response.get("is_task_complete", False):
        response = jsonify({
            "resource-assign-agent": {
                "id": task_id,
                "status": "error",
                "response": agent_response.get("content", {})
            },
            "agent_responses": task_request.get("agent_responses", [])
        })
        response.status_code = 500
        return response

    # Success: return status="success"
    return jsonify({
        "resource-assign-agent": {
            "id": task_id,
            "status": "success",
            "response": agent_response.get("content", {})
        },
        "agent_responses": task_request.get("agent_responses", [])
    })

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5013))
    print(f"Resource Assign Agent server starting on port {port}")
    app.run(host="0.0.0.0", port=port) 
