import sequelize from "./config/db.js";
import Disaster from "./models/Disaster.js";
import Resource from "./models/Resource.js";
import DisasterRequest from "./models/DisasterRequest.js";
import ResourceCenter from "./models/ResourceCenter.js";
import User from "./models/user.js";
import Admin from "./models/admin.js";
import FirstResponder from "./models/FirstResponder.js";
import News from "./models/News.js";

async function seedDatabase() {
  // Insert disasters
  await Disaster.bulkCreate([
    {
      name: "Flood",
      type: "natural",
      severity: "high",
      details: "Severe flooding due to heavy rains and river overflow",
    },
    {
      name: "Earthquake",
      type: "natural",
      severity: "critical",
      details: "Strong earthquake causing widespread damage",
    },
    {
      name: "HouseholdFire",
      type: "man-made",
      severity: "medium",
      details: "Fire incident in residential buildings",
    },
    {
      name: "Wildfire",
      type: "natural",
      severity: "high",
      details: "Forest fire spreading rapidly due to dry conditions",
    },
    {
      name: "Tsunami",
      type: "natural",
      severity: "medium",
      details: "Severe tsunami causing widespread damage",
    },
    {
      name: "Landslide",
      type: "natural",
      severity: "high",
      details: "Landslide",
    },
    { name: "Other", type: "natural", severity: "medium", details: "other" },
    //{ name: 'Industrial Fire', type: 'man-made', severity: 'high', details: 'Fire outbreak in factory or industrial plant' },
  ]);

  // Insert resources
  await Resource.bulkCreate([
    { type: "Human", name: "Emergency medical staff" },
    { type: "Human", name: "Search and rescue teams" },
    { type: "Human", name: "Crisis communications teams" },
    { type: "Material", name: "Bottled water" },
    { type: "Material", name: "Food rations" },
    { type: "Material", name: "First aid kits" },
    { type: "Financial", name: "Emergency relief funds" },
    { type: "Financial", name: "Housing assistance payments" },
    { type: "Financial", name: "Disaster pay provisions" },
    { type: "Equipment", name: "Radios and satellite phones" },
    { type: "Equipment", name: "Generators" },
    { type: "Equipment", name: "Fire extinguishers" },
    { type: "Facility", name: "Emergency shelters" },
    { type: "Facility", name: "Hospitals" },
    { type: "Facility", name: "Emergency operations centers" },
    { type: "Infrastructure", name: "Portable toilets" },
    { type: "Infrastructure", name: "Temporary bridges" },
    { type: "Infrastructure", name: "Waste management equipment" },
  ]);

  await User.bulkCreate([
    {
      name: "Nimal Perera",
      nic: "902345678V",
      address: "No. 12, Galle Road, Colombo 03",
      contactNumber: "0771234567",
      email: "sample@gmail.com",
      type: "victim",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma",
    },
    {
      name: "Kamalani Fernando",
      nic: "200245678901",
      address: "25/A, Station Road, Negombo",
      contactNumber: "0719876543",
      email: "kamalani.fernando@example.com",
      type: "victim",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma",
    },
    {
      name: "Sunil Jayawardena",
      nic: "801234567V",
      address: "45/2, Kandy Road, Kurunegala",
      contactNumber: "0751112233",
      email: "sunil.j@example.com",
      type: "victim",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma",
    },
    {
      name: "Dilani Rathnayake",
      nic: "991234567V",
      address: "10, Temple Lane, Anuradhapura",
      contactNumber: "0782223344",
      email: "dilani.r@example.com",
      type: "victim",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma",
    },
    {
      name: "Tharindu Senanayake",
      nic: "200134567890",
      address: "67/B, Lake View, Matara",
      contactNumber: "0763456789",
      email: "tharindu.s@example.com",
      type: "victim",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma",
    },
  ]);

  await DisasterRequest.bulkCreate([
    {
      name: "Tharindu Rathnayeka",
      userId: 2,
      disasterId: 1,
      severity: "MEDIUM",
      status: "PENDING",
      details: "Train derailment near railway station.",
      affectedCount: 20,
      contactNo: "0756677889",
      latitude: 6.8697,
      longitude: 79.9221,
      image: null,
      voice: null,
      isVerified: false,
      created_at: new Date("2021-06-01T10:00:00Z"),
      updated_at: new Date("2021-06-01T10:00:00Z"),
    },
    {
      name: "Kalpana Perera",
      userId: 2,
      disasterId: 2,
      severity: "MEDIUM",
      status: "PENDING",
      details: "Train derailment near railway station.",
      affectedCount: 20,
      contactNo: "0756677889",
      latitude: 6.8697,
      longitude: 79.9221,
      image: null,
      voice: null,
      isVerified: true,
      created_at: new Date("2024-06-01T10:00:00Z"),
      updated_at: new Date("2024-06-01T10:00:00Z"),
    },
    {
      name: "Kamal Fernando",
      userId: 2,
      disasterId: 3,
      severity: "HIGH",
      status: "IN_PROGRESS",
      details: "Flooding reported in town area.",
      affectedCount: 100,
      contactNo: "0712345678",
      latitude: 6.8171,
      longitude: 80.0217,
      image: null,
      voice: null,
      isVerified: false,
      created_at: new Date("2022-07-15T09:00:00Z"),
      updated_at: new Date("2022-07-15T10:00:00Z"),
    },
    {
      name: "Kamal Fernando",
      userId: 2,
      disasterId: 4,
      severity: "HIGH",
      status: "IN_PROGRESS",
      details: "Flooding reported in town area.",
      affectedCount: 100,
      contactNo: "0712345678",
      latitude: 6.8171,
      longitude: 80.0217,
      image: null,
      voice: null,
      isVerified: true,
      created_at: new Date("2022-07-15T09:00:00Z"),
      updated_at: new Date("2022-07-15T10:00:00Z"),
    },
    {
      name: "Dilani Perera",
      userId: 2,
      disasterId: 5,
      severity: "LOW",
      status: "IN_PROGRESS",
      details: "Minor earthquake with no damage reported.",
      affectedCount: 0,
      contactNo: "0771234567",
      latitude: 6.7967,
      longitude: 79.8905,
      image: null,
      voice: null,
      isVerified: false,
      created_at: new Date("2024-08-20T11:00:00Z"),
      updated_at: new Date("2024-08-20T12:00:00Z"),
    },
    {
      name: "Aruna Prasad",
      userId: 2,
      disasterId: 3,
      severity: "LOW",
      status: "IN_PROGRESS",
      details: "Minor earthquake with no damage reported.",
      affectedCount: 0,
      contactNo: "0771234567",
      latitude: 6.7967,
      longitude: 79.890,
      image: null,
      voice: null,
      isVerified: true,
      created_at: new Date("2024-08-20T11:00:00Z"),
      updated_at: new Date("2024-08-20T12:00:00Z"),
    },
    {
      name: "Nimal",
      userId: 1,
      disasterId: 1,
      severity: "HIGH",
      status: "PENDING",
      details: "Heavy flooding after continuous rain in low-lying areas.",
      affectedCount: 150,
      contactNo: "0771234567",
      latitude: 6.84950,
      longitude: 80.00869,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Nimal",
      userId: 1,
      disasterId: 5,
      severity: "HIGH",
      status: "PENDING",
      details: "Heavy flooding after continuous rain in low-lying areas.",
      affectedCount: 150,
      contactNo: "0771234567",
      latitude: 6.84950,
      longitude: 80.00869,
      district: "Kalutara District",
      province: "Western Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Kamalani",
      userId: 2,
      disasterId: 1,
      severity: "CRITICAL",
      status: "PENDING",
      details: "Seismic activity reported with strong tremors felt.",
      affectedCount: 300,
      contactNo: "0712345678",
      latitude: 6.79554,
      longitude: 79.94644,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Kamalani",
      userId: 2,
      disasterId: 5,
      severity: "CRITICAL",
      status: "PENDING",
      details: "Seismic activity reported with strong tremors felt.",
      affectedCount: 300,
      contactNo: "0712345678",
      latitude: 6.90159,
      longitude: 79.97549,
      district: "Kalutara District",
      province: "Western Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Sunil",
      userId: 3,
      disasterId: 5,
      severity: "MEDIUM",
      status: "PENDING",
      details: "Fire in residential area controlled by fire brigade.",
      affectedCount: 4,
      contactNo: "0769876543",
      latitude: 6.87923,
      longitude: 79.92506,
      district: "Kalutara District",
      province: "Western Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Sunil",
      userId: 4,
      disasterId: 1,
      severity: "HIGH",
      status: "PENDING",
      details: "Forest fire spreading across dry regions.",
      affectedCount: 60,
      contactNo: "0701234567",
      latitude: 6.908526,
      longitude: 80.00222,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Dilani",
      userId: 5,
      disasterId: 1,
      severity: "MEDIUM",
      status: "PENDING",
      details: "Possible tsunami threat after offshore earthquake.",
      affectedCount: 0,
      contactNo: "0752233445",
      latitude: 6.876034,
      longitude: 79.93464,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Tharindu",
      userId: 1,
      disasterId: 1,
      severity: "HIGH",
      status: "PENDING",
      details: "Roads blocked due to major landslide.",
      affectedCount: 35,
      contactNo: "0745566778",
      latitude: 6.876034,
      longitude: 79.93464,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Tharindu",
      userId: 1,
      disasterId: 1,
      severity: "HIGH",
      status: "PENDING",
      details: "Roads blocked due to major landslide.",
      affectedCount: 35,
      contactNo: "0745566778",
      latitude: 6.87923,
      longitude: 79.92506,
      district: "Kalutara District",
      province: "Western Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Nimal",
      userId: 1,
      disasterId: 2,
      severity: "CRITICAL",
      status: "PENDING",
      details: "Toxic chemical spill in industrial zone.",
      affectedCount: 25,
      contactNo: "0783456789",
      latitude: 6.10534,
      longitude: 80.11578,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Kamalani",
      userId: 2,
      disasterId: 2,
      severity: "HIGH",
      status: "PENDING",
      details: "Cyclonic winds expected within 48 hours.",
      affectedCount: 200,
      contactNo: "0719988776",
      latitude: 7.321732,
      longitude: 80.595478,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Sunil",
      userId: 3,
      disasterId: 2,
      severity: "HIGH",
      status: "PENDING",
      details: "Bridge collapsed due to heavy vehicle load.",
      affectedCount: 5,
      contactNo: "0791122334",
      latitude: 7.282415,
      longitude: 80.572913,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Dilani",
      userId: 4,
      disasterId: 2,
      severity: "MEDIUM",
      status: "PENDING",
      details: "Prolonged dry season affecting crops.",
      affectedCount: 400,
      contactNo: "0779988776",
      latitude: 6.09112,
      longitude: 80.23448,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Dilani",
      userId: 4,
      disasterId: 5,
      severity: "MEDIUM",
      status: "PENDING",
      details: "Prolonged dry season affecting crops.",
      affectedCount: 400,
      contactNo: "0779988776",
      latitude: 6.53938,
      longitude: 80.09904,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Tharindu",
      userId: 5,
      disasterId: 2,
      severity: "LOW",
      status: "PENDING",
      details: "Multi-vehicle collision on highway.",
      affectedCount: 3,
      contactNo: "0704455667",
      latitude: 7.311892,
      longitude: 80.569882,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Tharindu",
      userId: 5,
      disasterId: 2,
      severity: "MEDIUM",
      status: "PENDING",
      details: "Train derailment near railway station.",
      affectedCount: 20,
      contactNo: "0756677889",
      latitude: 7.9403,
      longitude: 81.0188,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Tharindu",
      userId: 5,
      disasterId: 1,
      severity: "CRITICAL",
      status: "PENDING",
      details: "Explosion in apartment due to gas leak.",
      affectedCount: 10,
      contactNo: "0765544332",
      latitude: 6.6828,
      longitude: 80.3998,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Dilani",
      userId: 4,
      disasterId: 1,
      severity: "HIGH",
      status: "PENDING",
      details: "Large-scale fire in industrial facility.",
      affectedCount: 40,
      contactNo: "0745566778",
      latitude: 7.289614,
      longitude: 80.599721,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Nimal",
      userId: 1,
      disasterId: 1,
      severity: "MEDIUM",
      status: "PENDING",
      details: "City-wide blackout due to storm damage.",
      affectedCount: 500,
      contactNo: "0774433221",
      latitude: 6.09112,
      longitude: 80.23448,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Nimal",
      userId: 1,
      disasterId: 4,
      severity: "HIGH",
      status: "PENDING",
      details: "Oil spill near shipping yard threatening marine life.",
      affectedCount: 0,
      contactNo: "0786677885",
      latitude: 7.297245,
      longitude: 80.610543,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: true,
    },
    {
      name: "Nimal",
      userId: 1,
      disasterId: 4,
      severity: "HIGH",
      status: "PENDING",
      details: "Tornado observed tearing through village.",
      affectedCount: 60,
      contactNo: "0729988776",
      latitude: 6.03809,
      longitude: 80.20729,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Nimal",
      userId: 1,
      disasterId: 3,
      severity: "CRITICAL",
      status: "PENDING",
      details: "Collapse in gem mining area with workers trapped.",
      affectedCount: 12,
      contactNo: "0715566774",
      latitude: 7.320112,
      longitude: 80.580774,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Kamalani",
      userId: 2,
      disasterId: 3,
      severity: "LOW",
      status: "PENDING",
      details: "Unexpected dust storm with poor visibility.",
      affectedCount: 0,
      contactNo: "0771112233",
      latitude: 6.03809,
      longitude: 80.20729,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
    {
      name: "Kamalani",
      userId: 3,
      disasterId: 2,
      severity: "CRITICAL",
      status: "PENDING",
      details: "Old building collapse due to poor construction.",
      affectedCount: 8,
      contactNo: "0733322110",
      latitude: 6.10534,
      longitude: 80.11578,
      district: "Galle District",
      province: "Southern Province",
      image: null,
      voice: null,
      isVerified: false,
    },
  ]);

  await Admin.bulkCreate([
    {
      name: "Inspector Wickramasinghe",
      NIC: "8012345618",
      contactNumber: "0771234561",
      email: "admin@gmail.com",
      description: "Head of local police operations",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    },
    {
      name: "Officer Janaka Perera",
      NIC: "7512345690",
      contactNumber: "0712345678",
      email: "admin2@gmail.com",
      description: "Disaster response coordinator - Southern Province",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    },
    {
      name: "Chief Kamalini De Silva",
      NIC: "6812345678",
      contactNumber: "0723456789",
      email: "admin3@gmail.com",
      description: "National emergency response supervisor",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    },
    {
      name: "Inspector Gunasekara",
      NIC: "7812345678",
      contactNumber: "0734567890",
      email: "admin20@gmail.com",
      description: "Head of local police operations",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"

    }
  ]
  );


  const centerLat = 6.81;
  const centerLong = 79.87;
  const radiusInKm = 25;

  function getRandomLatLong(centerLat, centerLong, radiusInKm) {
    const radiusInDegrees = radiusInKm / 111; // Rough conversion: 1 degree latitude ~111km

    // Random distance and angle
    const u = Math.random();
    const v = Math.random();
    const w = radiusInDegrees * Math.sqrt(u);
    const t = 2 * Math.PI * v;
    const x = w * Math.cos(t);
    const y = w * Math.sin(t);

    // Adjust longitude based on latitude
    const newLat = centerLat + y;
    const newLong = centerLong + x / Math.cos(centerLat * (Math.PI / 180));

    return { lat: newLat, long: newLong };
  }

  const resources = await Resource.findAll();


//   const resourceCentersData = [
//   {
//     resourceId: 1,
//     name: "Medical Center",
//     lat: 6.839512,
//     long: 79.965421,
//     district: "Colombo",
//     province: "Western",
//     count: 85,
//     contactNumber: "+94-11-5550100",
//     used: 23,
//   },
//   {
//     resourceId: 2,
//     name: "Rescue Base",
//     lat: 6.842113,
//     long: 79.969782,
//     district: "Colombo",
//     province: "Western",
//     count: 72,
//     contactNumber: "+94-91-5550101",
//     used: 30,
//   },
//   {
//     resourceId: 3,
//     name: "Food Station",
//     lat: 6.837201,
//     long: 79.962897,
//     district: "Colombo",
//     province: "Western",
//     count: 64,
//     contactNumber: "+94-21-5550102",
//     used: 15,
//   },
//   {
//     resourceId: 4,
//     name: "Army Post",
//     lat: 6.841923,
//     long: 79.959782,
//     district: "Colombo",
//     province: "Western",
//     count: 88,
//     contactNumber: "+94-81-5550103",
//     used: 40,
//   },
//   {
//     resourceId: 5,
//     name: "Relief Camp",
//     lat: 6.851243,
//     long: 79.903121,
//     district: "Colombo",
//     province: "Western",
//     count: 49,
//     contactNumber: "+94-41-5550104",
//     used: 20,
//   },
//   {
//     resourceId: 6,
//     name: "Supply Depot",
//     lat: 6.853412,
//     long: 79.906512,
//     district: "Colombo",
//     province: "Western",
//     count: 91,
//     contactNumber: "+94-33-5550105",
//     used: 33,
//   },
//   {
//     resourceId: 7,
//     name: "First Aid",
//     lat: 6.850923,
//     long: 79.899876,
//     district: "Colombo",
//     province: "Western",
//     count: 78,
//     contactNumber: "+94-25-5550106",
//     used: 18,
//   },
//   {
//     resourceId: 8,
//     name: "Water Point",
//     lat: 6.848421,
//     long: 79.902731,
//     district: "Colombo",
//     province: "Western",
//     count: 55,
//     contactNumber: "+94-24-5550107",
//     used: 12,
//   },
//   {
//     resourceId: 9,
//     name: "Shelter Zone",
//     lat: 6.852012,
//     long: 79.897332,
//     district: "Colombo",
//     province: "Western",
//     count: 67,
//     contactNumber: "+94-55-5550108",
//     used: 21,
//   },
//   {
//     resourceId: 10,
//     name: "Command Center",
//     lat: 6.840541,
//     long: 79.968732,
//     district: "Colombo",
//     province: "Western",
//     count: 95,
//     contactNumber: "+94-37-5550109",
//     used: 45,
//   },
//   {
//     resourceId: 11,
//     name: "Command Center",
//     lat: 6.843891,
//     long: 79.971243,
//     district: "Colombo",
//     province: "Western",
//     count: 95,
//     contactNumber: "+94-37-5550109",
//     used: 45,
//   },
//   {
//     resourceId: 12,
//     name: "Shelter Zone",
//     lat: 6.851145,
//     long: 79.899532,
//     district: "Colombo",
//     province: "Western",
//     count: 90,
//     contactNumber: "+94-37-5550109",
//     used: 30,
//   },
//   {
//     resourceId: 13,
//     name: "First Aid",
//     lat: 6.838912,
//     long: 79.966123,
//     district: "Colombo",
//     province: "Western",
//     count: 95,
//     contactNumber: "+94-37-5550109",
//     used: 45,
//   },
//   {
//     resourceId: 14,
//     name: "Water Point",
//     lat: 6.853041,
//     long: 79.905112,
//     district: "Colombo",
//     province: "Western",
//     count: 95,
//     contactNumber: "+94-37-5550109",
//     used: 45,
//   },
//   {
//     resourceId: 15,
//     name: "Food Station",
//     lat: 6.852741,
//     long: 79.902231,
//     district: "Colombo",
//     province: "Western",
//     count: 95,
//     contactNumber: "+94-37-5550109",
//     used: 45,
//   },
//   {
//     resourceId: 16,
//     name: "Medical Center",
//     lat: 6.839424,
//     long: 79.967431,
//     district: "Colombo",
//     province: "Western",
//     count: 100,
//     contactNumber: "+94-37-5550109",
//     used: 45,
//   },

//   // ✅ Added 10 more nearby resources
//   // {
//   //   resourceId: 17,
//   //   name: "Relief Camp",
//   //   lat: 6.841523,
//   //   long: 79.970112,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 70,
//   //   contactNumber: "+94-11-5550110",
//   //   used: 25,
//   // },
//   // {
//   //   resourceId: 18,
//   //   name: "Medical Center",
//   //   lat: 6.850632,
//   //   long: 79.904912,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 82,
//   //   contactNumber: "+94-11-5550111",
//   //   used: 20,
//   // },
//   // {
//   //   resourceId: 19,
//   //   name: "Food Station",
//   //   lat: 6.838712,
//   //   long: 79.969512,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 60,
//   //   contactNumber: "+94-11-5550112",
//   //   used: 18,
//   // },
//   // {
//   //   resourceId: 20,
//   //   name: "Army Post",
//   //   lat: 6.852541,
//   //   long: 79.900743,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 76,
//   //   contactNumber: "+94-11-5550113",
//   //   used: 32,
//   // },
//   // {
//   //   resourceId: 21,
//   //   name: "Rescue Base",
//   //   lat: 6.839932,
//   //   long: 79.964823,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 90,
//   //   contactNumber: "+94-11-5550114",
//   //   used: 29,
//   // },
//   // {
//   //   resourceId: 22,
//   //   name: "Supply Depot",
//   //   lat: 6.853732,
//   //   long: 79.903232,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 110,
//   //   contactNumber: "+94-11-5550115",
//   //   used: 50,
//   // },
//   // {
//   //   resourceId: 23,
//   //   name: "Shelter Zone",
//   //   lat: 6.842341,
//   //   long: 79.968321,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 74,
//   //   contactNumber: "+94-11-5550116",
//   //   used: 22,
//   // },
//   // {
//   //   resourceId: 24,
//   //   name: "Water Point",
//   //   lat: 6.851932,
//   //   long: 79.905732,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 65,
//   //   contactNumber: "+94-11-5550117",
//   //   used: 19,
//   // },
//   // {
//   //   resourceId: 25,
//   //   name: "First Aid",
//   //   lat: 6.840121,
//   //   long: 79.966821,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 58,
//   //   contactNumber: "+94-11-5550118",
//   //   used: 16,
//   // },
//   // {
//   //   resourceId: 26,
//   //   name: "Command Center",
//   //   lat: 6.849732,
//   //   long: 79.900932,
//   //   district: "Colombo",
//   //   province: "Western",
//   //   count: 102,
//   //   contactNumber: "+94-11-5550119",
//   //   used: 48,
//   // }
// ];

const resourceCentersData = [
  {
    resourceId: 1,
    name: "Vijerama Medical Center",
    lat: 6.850421,
    long: 79.908732,
    district: "Colombo",
    province: "Western",
    count: 85,
    contactNumber: "+94-11-5550100",
    used: 23,
  },
  {
    resourceId: 2,
    name: "Rescue Base",
    lat: 6.857213,
    long: 79.899912,
    district: "Colombo",
    province: "Western",
    count: 72,
    contactNumber: "+94-91-5550101",
    used: 30,
  },
  {
    resourceId: 3,
    name: "Food Station",
    lat: 6.855912,
    long: 79.902781,
    district: "Colombo",
    province: "Western",
    count: 64,
    contactNumber: "+94-21-5550102",
    used: 15,
  },
  {
    resourceId: 4,
    name: "Vijerama Army Post",
    lat: 6.849723,
    long: 79.906542,
    district: "Colombo",
    province: "Western",
    count: 88,
    contactNumber: "+94-81-5550103",
    used: 40,
  },
  {
    resourceId: 5,
    name: "Relief Camp",
    lat: 6.856142,
    long: 79.900431,
    district: "Colombo",
    province: "Western",
    count: 49,
    contactNumber: "+94-41-5550104",
    used: 20,
  },
  {
    resourceId: 6,
    name: "Vijerama Supply Depot",
    lat: 6.854213,
    long: 79.907612,
    district: "Colombo",
    province: "Western",
    count: 91,
    contactNumber: "+94-33-5550105",
    used: 33,
  },
  {
    resourceId: 7,
    name: "First Aid",
    lat: 6.851213,
    long: 79.902231,
    district: "Colombo",
    province: "Western",
    count: 78,
    contactNumber: "+94-25-5550106",
    used: 18,
  },
  {
    resourceId: 8,
    name: "Water Point",
    lat: 6.852841,
    long: 79.905432,
    district: "Colombo",
    province: "Western",
    count: 55,
    contactNumber: "+94-24-5550107",
    used: 12,
  },
  {
    resourceId: 9,
    name: "Vijerama Shelter Zone",
    lat: 6.857912,
    long: 79.898512,
    district: "Colombo",
    province: "Western",
    count: 67,
    contactNumber: "+94-55-5550108",
    used: 21,
  },
  {
    resourceId: 10,
    name: "Vijerama Command Center",
    lat: 6.848541,
    long: 79.910123,
    district: "Colombo",
    province: "Western",
    count: 95,
    contactNumber: "+94-37-5550109",
    used: 45,
  },
  {
    resourceId: 11,
    name: "Command Center",
    lat: 6.855431,
    long: 79.908542,
    district: "Colombo",
    province: "Western",
    count: 95,
    contactNumber: "+94-37-5550109",
    used: 45,
  },
  {
    resourceId: 12,
    name: "Shelter Zone 1",
    lat: 6.850112,
    long: 79.901632,
    district: "Colombo",
    province: "Western",
    count: 90,
    contactNumber: "+94-37-5550109",
    used: 30,
  },
  {
    resourceId: 13,
    name: "First Aid",
    lat: 6.849612,
    long: 79.907421,
    district: "Colombo",
    province: "Western",
    count: 95,
    contactNumber: "+94-37-5550109",
    used: 45,
  },
  {
    resourceId: 14,
    name: "Shelter Zone 2",
    lat: 6.853341,
    long: 79.903912,
    district: "Colombo",
    province: "Western",
    count: 95,
    contactNumber: "+94-37-5550109",
    used: 45,
  },
  {
    resourceId: 15,
    name: "Food Station",
    lat: 6.855212,
    long: 79.906321,
    district: "Colombo",
    province: "Western",
    count: 95,
    contactNumber: "+94-37-5550109",
    used: 45,
  },
  {
    resourceId: 16,
    name: "Medical Center",
    lat: 6.851424,
    long: 79.908231,
    district: "Colombo",
    province: "Western",
    count: 100,
    contactNumber: "+94-37-5550109",
    used: 45,
  },
];



  await ResourceCenter.bulkCreate(resourceCentersData);

  await FirstResponder.bulkCreate([
    {
      name: "Inspector Wickramasinghe",
      nic: "801234561V",
      resourceCenterId: 1,
      address: "456 Police Station Road",
      contactNumber: "0771234561",
      email: "fr@gmail.com",
      type: "police",
      description: "Head of local police operations",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    },
    {
      name: "Officer Nadeesha Silva",
      nic: "902345678V",
      resourceCenterId: 2,
      address: "123 Main Street, Galle",
      contactNumber: "0712345678",
      email: "nadeesha@example.com",
      type: "police",
      description: "Officer in charge of regional response unit",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    },
    {
      name: "Sergeant Dilan Jayasuriya",
      nic: "911234567V",
      resourceCenterId: 3,
      address: "78 Station Lane, Kandy",
      contactNumber: "0756781234",
      email: "dilan@example.com",
      type: "police",
      description: "Emergency deployment specialist",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    },
    {
      name: "Chief Inspector Suranga Perera",
      nic: "861234567V",
      resourceCenterId: 1,
      address: "99 Defense Avenue, Colombo",
      contactNumber: "0765432187",
      email: "suranga@example.com",
      type: "police",
      description: "Chief inspector of national coordination",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    },
    {
      name: "Officer Ishara Fernando",
      nic: "951234567V",
      resourceCenterId: 4,
      address: "12 Central Road, Matara",
      contactNumber: "0781234567",
      email: "ishara@example.com",
      type: "police",
      description: "Handles ground-level emergency coordination",
      password: "$2b$10$GXGJL7f1/rin7rAkkWrVi.XztQBbtXMQO.B3A351CaS71F5MxA1Ma"
    }
  ]);

  // Seed dummy news
  await News.bulkCreate([
    {
      title: "Major Flooding in Wellawatta",
      disasterId: 1,
      disasterRequestId: null,
      type: "natural",
      severity: "HIGH",
      details:
        "Severe flooding affecting Wellawatta area after heavy monsoon rains. Evacuations underway and temporary shelters opened.",
      affectedCount: 250,
      contactNo: "119",
      latitude: 6.8700,
      longitude: 79.8650,
      district: "Colombo",
      province: "Western",
      status: "IN_PROGRESS",
    },
    {
      title: "Commercial Complex Fire Contained in Kandy",
      disasterId: 3,
      disasterRequestId: null,
      type: "man-made",
      severity: "CRITICAL",
      details:
        "Fire at Central Plaza commercial complex contained after 4-hour operation. Building closed for safety inspection.",
      affectedCount: 120,
      contactNo: "110",
      latitude: 7.2906,
      longitude: 80.6337,
      district: "Kandy",
      province: "Central",
      status: "COMPLETED",
    },
    {
      title: "Landslide Warning Issued for Hill Country",
      disasterId: 6,
      disasterRequestId: null,
      type: "natural",
      severity: "MEDIUM",
      details:
        "Disaster Management Center issues landslide warning after continuous rainfall. Residents advised to be vigilant.",
      affectedCount: 300,
      contactNo: "117",
      latitude: 6.0535,
      longitude: 80.2210,
      district: "Galle",
      province: "Southern",
      status: "PENDING",
    },
  ]);


  console.log("Seeding completed");
}

export default seedDatabase;
